# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'es'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.asambleista:
        class: App\Admin\AsambleistaAdmin
        arguments: [~, App\Entity\Asambleista, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Asambleista }
        public: true

    admin.consejeros_superiores:
        class: App\Admin\ConsejeroSuperiorAdmin
        arguments: [~, App\Entity\ConsejeroSuperior, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 'Consejeros Superiores' }
        public: true

    admin.director_instituto:
        class: App\Admin\DirectorInstitutoAdmin
        arguments: [~, App\Entity\DirectorInstituto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 'Director de Instituto' }
        public: true

    admin.persona:
        class: App\Admin\PersonaAdmin
        arguments: [~, App\Entity\Persona, App\Controller\PersonaController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Persona }
        public: true

    admin.instituto:
        class: App\Admin\InstitutoAdmin
        arguments: [~, App\Entity\Instituto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Instituto, show_in_dashboard: false}
        public: true

    admin.proyecto_investigacion:
        class: App\Admin\ProyectoInvestigacionAdmin
        arguments: [~, App\Entity\ProyectoInvestigacion, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 'Proyecto de Investigacion' }
        public: true
        calls:
        - [addChild, ['@admin.miembro_proyecto', 'proyecto']]

    admin.carrera:
        class: App\Admin\CarreraAdmin
        arguments: [~, App\Entity\Carrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Carrera }
        public: true

    admin.director_carrera:
        class: App\Admin\DirectorCarreraAdmin
        arguments: [~, App\Entity\DirectorCarrera, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 'Director de Carrera' }
        public: true

    admin.coordinador_materia:
        class: App\Admin\CoordinadorMateriaAdmin
        arguments: [~, App\Entity\CoordinadorMateria, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: 'Coordinador de Materia' }
        public: true
        calls:
        - [addChild, ['@admin.materia', 'coordinador']]

    admin.materia:
        class: App\Admin\MateriaAdmin
        arguments: [~, App\Entity\Materia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Materia, show_in_dashboard: false}
        public: true

    admin.miembro_proyecto:
        class: App\Admin\MiembroProyectoAdmin
        arguments: [~, App\Entity\MiembroProyecto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Miembro de Proyecto", show_in_dashboard: false}
        public: true

    admin.proyecto_extension:
        class: App\Admin\ProyectoExtensionAdmin
        arguments: [~, App\Entity\ProyectoExtension, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Proyecto de Extension" }
        public: true
        calls:
        - [addChild, ['@admin.miembro_proyecto', 'proyecto']]

    admin.rol_proyecto:
        class: App\Admin\RolProyectoAdmin
        arguments: [~, App\Entity\RolProyecto, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Rol de Proyecto" }
        public: true
        calls:
        - [addChild, ['@admin.miembro_proyecto', 'rol']]

    edit_roles_subscriber:
        class: App\Form\EventSubscriber\EditRoles
        tags:
            - { name: kernel.event_subscriber }

    admin.comision_consejo_superior:
        class: App\Admin\ComisionConsejoSuperiorAdmin
        arguments: [~, App\Entity\ComisionConsejoSuperior, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ComisionConsejoSuperior }
        public: true
        calls:
        - [addChild, ['@admin.miembro_ccs', 'comisionConsejoSuperior']]

    admin.miembro_ccs:
        class: App\Admin\MiembroCCSAdmin
        arguments: [~, App\Entity\MiembroCCS, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MiembroCCS }
        public: true

    admin.rol_ccs:
        class: App\Admin\RolCCSAdmin
        arguments: [~, App\Entity\RolCCS, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: RolCCS }
        public: true

    admin.miembro_pps:
        class: App\Admin\MiembroPPSAdmin
        arguments: [~, App\Entity\MiembroPPS, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MiembroPPS, show_in_dashboard: false }
        public: true

    admin.pps:
        class: App\Admin\PPSAdmin
        arguments: [~, App\Entity\PPS, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: PPS }
        public: true
        calls:
        - [addChild, ['@admin.miembro_pps', 'pps']]

    admin.miembro_actividad_divulgacion:
        class: App\Admin\MiembroActividadDivulgacionAdmin
        arguments: [~, App\Entity\MiembroActividadDivulgacion, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MiembroActividadDivulgacion, show_in_dashboard: false}
        public: true

    admin.actividad_divulgacion:
        class: App\Admin\ActividadDivulgacionAdmin
        arguments: [~, App\Entity\ActividadDivulgacion, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ActividadDivulgacion }
        public: true

    admin.curso_extension:
        class: App\Admin\CursoExtensionAdmin
        arguments: [~, App\Entity\CursoExtension, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CursoExtension }
        public: true
        calls:
        - [addChild, ['@admin.miembro_curso_extension', 'cursoExtension']]

    admin.miembro_curso_extension:
        class: App\Admin\MiembroCursoExtensionAdmin
        arguments: [~, App\Entity\MiembroCursoExtension, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MiembroCursoExtension, show_in_dashboard: false}
        public: true

    admin.rector:
        class: App\Admin\RectorAdmin
        arguments: [~, App\Entity\Rector, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Rector }
        public: true

    admin.area:
        class: App\Admin\AreaAdmin
        arguments: [~, App\Entity\Area, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Area }
        public: true

    admin.responsable_area:
        class: App\Admin\ResponsableAreaAdmin
        arguments: [~, App\Entity\ResponsableArea, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ResponsableArea }
        public: true

    admin.pasantia:
        class: App\Admin\PasantiaAdmin
        arguments: [~, App\Entity\Pasantia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pasantia }
        public: true
        calls:
        - [addChild, ['@admin.miembro_pasantia', 'pasantia']]

    admin.miembro_pasantia:
        class: App\Admin\MiembroPasantiaAdmin
        arguments: [~, App\Entity\MiembroPasantia, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MiembroPasantia, show_in_dashboard: false}
        public: true

    admin.voluntariado:
        class: App\Admin\VoluntariadoAdmin
        arguments: [~, App\Entity\Voluntariado, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Voluntariado }
        public: true
        calls:
        - [addChild, ['@admin.miembro_voluntariado', 'voluntariado']]

    admin.miembro_voluntariado:
        class: App\Admin\MiembroVoluntariadoAdmin
        arguments: [~, App\Entity\MiembroVoluntariado, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MiembroVoluntariado, show_in_dashboard: false}
        public: true

    admin.programa:
        class: App\Admin\ProgramaAdmin
        arguments: [~, App\Entity\Programa, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Programa }
        public: true
        calls:
        - [addChild, ['@admin.miembro_programa', 'programa']]

    admin.miembro_programa:
        class: App\Admin\MiembroProgramaAdmin
        arguments: [~, App\Entity\MiembroPrograma, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MiembroPrograma, show_in_dashboard: false}
        public: true

    admin.vinculador:
        class: App\Admin\VinculadorAdmin
        arguments: [~, App\Entity\Vinculador, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Vinculador }
        public: true

    admin.publicacion:
        class: App\Admin\PublicacionAdmin
        arguments: [~, App\Entity\Publicacion, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Publicacion }
        public: true

    admin.movilidad_conurbano_sur:
        class: App\Admin\MovilidadConurbanoSurAdmin
        arguments: [~, App\Entity\MovilidadConurbanoSur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MovilidadConurbanoSur }
        public: true

    admin.movilidad_rtf:
        class: App\Admin\MovilidadRTFAdmin
        arguments: [~, App\Entity\MovilidadRTF, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: MovilidadRTF }
        public: true

    admin.beca_befat:
        class: App\Admin\BecaBefatAdmin
        arguments: [~, App\Entity\BecaBefat, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: BecaBefat }
        public: true

    admin.secretario:
        class: App\Admin\SecretarioAdmin
        arguments: [~, App\Entity\Secretario, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Secretario }
        public: true

    admin.sub_secretario:
        class: App\Admin\SubSecretarioAdmin
        arguments: [~, App\Entity\SubSecretario, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SubSecretario }
        public: true

    admin.vice_rector:
        class: App\Admin\ViceRectorAdmin
        arguments: [~, App\Entity\ViceRector, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ViceRector }
        public: true
